name: Kyron Archive Server

services:
  proxy_cache:
    container_name: "kyron_redis"
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "redis_cache:/cache"
    command: ["redis-server"]
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 128M

  backend:
    container_name: "kyron_backend_api"
    ports:
      - "4000:4000"
    build:
      context: ./server
      dockerfile: Dockerfile

  client:
    container_name: Web dashboard
    build:
      dockerfile: ./web_dashboard/Dockerfile
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 128M

volumes:
  redis_cache:
