from kyron_shared.environment import KyronBaseEnvironment
from pathlib import Path
from typing import Optional

__all__ = [
    "KYRON_APP_CONFIG",
    "KyronFilesystem"
]

KYRON_APP_CONFIG = Path.home() / ".kyron_app_config"


class KyronFilesystem:
    """A set of utilities for scanning videos, metadata, and verifying downloaded content"""

    def __init__(self,
                 dir: str,
                 *,
                 envs: Optional[KyronBaseEnvironment] = None):
        if not Path(dir).is_dir():
            raise OSError("That ain't a directory fam")

        if Path(dir).is_file():
            raise OSError("Bruh I need folders, not FILES")

        self.set_directory = Path(dir)
        self.kyron_path = self.set_directory / ".kyron"

        if envs is None:
            self.executables = KyronBaseEnvironment()

        # directories
        self.raw_dir_contents = self.set_directory.iterdir()
        self.dir_contents = [f.name for f in self.raw_dir_contents]

    def has_kyron_directory(self) -> bool:
        """Checks if the directory has a valid `.kyron` subfolder, returns a boolean value"""
        is_valid_kyron_path = self.kyron_path.is_dir()

        # todo: make sure it detects other files such as config.json and other directories: logs/
        return is_valid_kyron_path

    def create_kyron_directory(self):
        # don't create if a `.kyron` directory is valid already
        if self.has_kyron_directory():
            return
        ...

    def _parse_metadata(self):
        """
        Appropiately parses metadata generated by yt-dlp, assuming they have the exact
        same format
        """
        ...

    def verify_downloads(self, *, autofix: bool = False):
        """
        Uses FFmpeg to ensure downloads are not corrupted in some way and fixes them

        Args:
            autofix (bool, optional): Enable to auto-fix corrupted videos, may convert them
            to an appropriate format if necessary. Defaults to False.
        """
        ...
