from .environment import KyronBaseEnvironment
from pathlib import Path


def path_to_str(path: Path | str) -> str:
    """A small utility to convert any `Path` type to `str`"""
    if isinstance(path, str):
        return path
    else:
        return str(path)


class KyronFilesystem:
    """A set of utilities for scanning videos, metadata, and verifying downloaded content"""

    def __init__(self, dir: str, envs: KyronBaseEnvironment):
        self.set_directory = Path(dir)
        self.ffmpeg_executable = envs.ffmpeg_dir

        self.kyron_path = self.set_directory / ".kyron"
        
        self.kyron_global_config = Path.home() / ".kyron_global"

    def has_kyron_directory(self) -> bool:
        """Checks if the directory has a valid `.kyron` subfolder, returns a boolean value"""
        is_valid_kyron_path = self.kyron_path.is_dir()

        # todo: make sure it detects other files such as config.json and other directories: logs/
        return is_valid_kyron_path

    def create_kyron_directory(self):
        # don't create if a `.kyron` directory is valid already
        if self.has_kyron_directory():
            return
        ...

    def _parse_metadata(self):
        """
        Appropiately parses metadata generated by yt-dlp, assuming they have the exact
        same format
        """
        ...

    def verify_downloads(self, *, autofix: bool = False):
        """
        Uses FFmpeg to ensure downloads are not corrupted in some way and fixes them

        Args:
            autofix (bool, optional): Enable to auto-fix corrupted videos, may convert them
            to an appropriate format if necessary. Defaults to False.
        """
        ...
